### PR TITLE
Add precinct level data for town of Acton

### PR DESCRIPTION
**Pull request by tdooner**
Hello, I'm a first time contributor and not quite sure I'm doing this correctly.

I used Tabula and a custom script to process the tabula output. Is it worth checking that stuff in? 
Where?

There are some other intermediate files (such as a list of all the candidates and their parties) that could be useful across all towns in MA.

Also where did the non-precinct level results come from?

Let me know if there's any other area of the project that might be better to work on, else I'll just keep working through Massachusetts.

### CODE REVIEW

**Comment by lephead** [comment]
in Massachusetts, precinct results come from each town clerk.  You have to contact them all.  Done it several times now.

**Comment by dwillis** [comment]
@tdooner thanks! your Acton file looks great, with one small thing: the name of the county should be capitalized. If you have other files that helped with processing, you can check them in as well in a `src` directory. The non-precinct results came from the same files, and we're happy to have you working through Massachusetts (I think @lephead has Boston).

**Comment by lephead** [comment]
Yes, I am doing Boston.

**Comment by tdooner** [comment]
Thanks @dwillis! I capitalized the county name.

**Comment by dwillis** [comment]
Thanks @tdooner!

**Pull request merged**
